"""Update new_column to LONGBLOB

Revision ID: 32cdf2fd68f5
Revises: c0c7b32e2860
Create Date: 2024-11-23 22:46:56.070571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32cdf2fd68f5'
down_revision = 'c0c7b32e2860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design_response_photo', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design_response_photo', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
