"""create tables

Revision ID: e070a03f744c
Revises: 
Create Date: 2024-11-26 21:20:12.256928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e070a03f744c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('birth_date', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('design',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('room', sa.String(length=255), nullable=False),
    sa.Column('like', sa.Boolean(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gpt_description', sa.String(length=500), nullable=True),
    sa.Column('gpt_photo', mysql.LONGBLOB(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(length=500), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['design.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_response_photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('response', mysql.LONGBLOB(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['design.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('design_response_photo')
    op.drop_table('design_response')
    op.drop_table('design')
    op.drop_table('user')
    # ### end Alembic commands ###
